[pytest]
# 默认命令行参数
addopts = -v -s --tb=short

# -v 显示每个测试方法的执行结果 显示进度百分比 更清楚地知道哪个测试通过了

# 测试文件搜索路径
testpaths = scripts

# 测试文件命名规则
python_files = test_*.py

# 测试类命名规则
python_classes = Test*

# 测试函数命名规则
python_functions = test_*

